### ISSUE TITLE
(bug) Aniplay video is empty 

### ISSUE THREAD

**Issue by Delmarcop52** [Dark25/aniyomi-extensions#106]
### Source information

Aniplay 14.7

### Source language

English

### Steps to reproduce

1.open aniplay 
2.search dragon ball kai
3.video is not empty 

### Expected behavior

The video is not empty 

### Actual behavior

The video empty 

### Aniyomi version

App version: 0.14.6-6678 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
is ok, update the extension
