### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by venkat2305** [Dark25/aniyomi-extensions#15]
### Describe why this should be added

https://github.com/user-attachments/assets/b775c0ce-d416-4695-b5b1-a12cfae10d10
Can you help me with this
I'm unable to add repo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open (or closed) issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
You must update aniyomi to the latest version 🐋

**Comment by bapeey** [comment]
@Dark25 the url is wrong btw, its pointing to aniyomi repo

**Comment by Dark25** [comment]
> @Dark25 the url is wrong btw, its pointing to aniyomi repo, also should be better to put the url in the readme.md for manual installation

Thanks, I will make the necessary changes. I hadn't realized that

**Comment by Dark25** [comment]
Fix
