### ISSUE TITLE
Aniwave giving error

### ISSUE THREAD

**Issue by MonomoySama** [Dark25/aniyomi-extensions#20]
### Source information

Aniwave 14.69

### Source language

English 

### Steps to reproduce

Open any content in this extension 

### Expected behavior

Should start playing

### Actual behavior

![Screenshot_2024-08-01-19-31-10-98](https://github.com/user-attachments/assets/08c91d99-80ba-4b2e-a19c-758c32e760e7)

### Aniyomi version

0.16.4.3

### Android version

Android 10

### Other details

Also they changed the domain, although this extension which is aniwave.to, still works, i think you should update it to their latest domain Aniwavetv.to , maybe this is why the error's coming?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
fix
