### ISSUE TITLE
AnimeFire - Error SocketTimeOutException

### ISSUE THREAD

**Issue by nomaxsnx** [Dark25/aniyomi-extensions#35]
### Source information

AnimeFire - 14.7

### Source language

Português

### Steps to reproduce

1 installation extension AnimeFire

### Expected behavior

![Screenshot_2024-08-13-21-59-30-109_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/34979276-78d5-40ba-944b-71cba0092c95)

### Actual behavior

Error TimeOut

### Aniyomi version

App version: 0.16.4.3 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
I have checked the URL and the website is down, let's see if they acquire a new domain or it comes back online

**Comment by Dark25** [comment]
I have checked the URL and the website is down, let's see if they acquire a new domain or it comes back online
