### ISSUE TITLE
 HiAnime

### ISSUE THREAD

**Issue by Delmarcop52** [Dark25/aniyomi-extensions#76]
### Source information

Hianime 14.43

### Source language

English/Japanese

### Steps to reproduce

1.Open HiAnime
2.Search Bungou Stray Dogs
3.Try to open an episode

### Expected behavior

The selected episode should play

### Actual behavior

Its showing a toast saying "Video list is empty"

### Aniyomi version

App version: 0.16.4.3-7809 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Delmarcop52** [comment]
![Screenshot_20240909-203621](https://github.com/user-attachments/assets/4022f1a2-c642-4462-9a5f-79e0606faf4d)

**Comment by Dark25** [comment]
I just tried it and it works perfectly
