### ISSUE TITLE
Https error 404

### ISSUE THREAD

**Issue by Delmarcop52** [Dark25/aniyomi-extensions#77]
### Source information

Anime pahe

### Source language

English

### Steps to reproduce

1.open animepahe
2.search kill la kill
3.trying to the episode

### Expected behavior

The video is working 

### Actual behavior

![Screenshot_20240911-091427](https://github.com/user-attachments/assets/6be121ff-ac63-4601-a00a-db6b738b74a9)

### Aniyomi version

App version: 0.16.4.3-7809 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
I have tested the extension and it is working fine.

**Comment by Dark25** [comment]
@Delmarcop52 have you updated the app and the extension?

**Comment by Delmarcop52** [comment]
Also aniplay is still not working

**Comment by Dark25** [comment]
aniplay has not been fixed yet, I hope to fix it soon :D

> Also aniplay is still not working
